### PR TITLE
Save and restore last pkg and launch file (address #4).

### PR DESCRIPTION
**Pull request by 130s**
@pschillinger sorry I didn't know until now that you assigned yourself to #4. If you have on-going work, please consider merge this if this looks good.

And I can't think of good test to add for now. Any idea?

### CODE REVIEW

**Comment by pschillinger** [comment]
Thanks for the PR @130s ! Yes, I assigned myself, but I had much less time than expected during the last weeks, so your support is very welcome.

Do you think it will be sufficient to store the index? I would expect problems if new packages in general or launch files in the stored package get added or removed, which should happen quite often in most development workspaces.

**Comment by 130s** [comment]
That sounds to me like a corner case but still a possible scenario. And I can probably add a test case for that, which I'll work on when I have time.

**Comment by pschillinger** [comment]
I changed the settings to store the name instead of the index to be more robust. In addition, launch arguments are now stored as well.

Let me know if this works for you.

**Comment by 130s** [comment]
Looks like working perfectly for me for now. Thanks!

**Pull request merged**
